name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  cached_network_image: ^3.3.0
  js: ^0.6.7
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_html: ^3.0.0-beta.2
  http: ^1.2.0
  supabase_flutter: ^2.8.4
  google_fonts: ^6.2.1
  url_launcher: ^6.2.3
  page_transition: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/T4LLogo.png
    - assets/images/placeholder.jpeg
    - assets/images/Facility.png
    - assets/images/noHuddle.jpg
    - assets/images/noHuddleCrop.jpg
    - assets/logos/
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

